workflow:
  rules:
    # For merge requests, create a pipeline.
    - if: '$CI_MERGE_REQUEST_IID'
    # For `master` branch, create a pipeline (this includes on schedules, pushes, merges, etc.).
    # - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    # Temporarly create Ci for every branch:
    - if: '$CI_COMMIT_BRANCH'
    # For tags, create a pipeline.
    - if: '$CI_COMMIT_TAG'
    # For stable branches, create a pipeline.
    - if: '$CI_COMMIT_BRANCH =~ /^[\d-]+-stable$/'
    #

stages:
  - test
  - test-2
  - test-3

default:
  image: golang:1.15
  tags:
    - gitlab-org

# Disable DIND for SAST because we need to execute a before_script in the gosec-sast job
variables:
  SAST_DISABLE_DIND: "true"

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

gosec-sast:
  before_script:
    - apk add make
    - make install

code_navigation:
  image: golang:latest
  allow_failure: true
  script:
    - go get github.com/sourcegraph/lsif-go/cmd/lsif-go
    - lsif-go
  artifacts:
    reports:
      lsif: dump.lsif

.test:
  # We limit concurrency because the integration tests execute _real_ actions in GitLab
  # By limiting the resource group we can ensure that only one test is run in parallel
  resource_group: test
  variables:
    GOPATH: "/builds/go"
    GIT_CLONE_PATH: $GOPATH/src/github.com/zaquestion/lab
  script:
    - go version
    - make test


test-1.13:
  stage: test
  extends: .test
  image: golang:1.13
  needs: []

test-1.14:
  stage: test-2
  extends: .test
  image: golang:1.14
  needs: [test-1.13]

test-1.15:
  stage: test-3
  extends: .test
  image: golang:1.15
  needs: [test-1.14]
